name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username ${{ secrets.DOCKERUSER }} --p ${{ secrets.DOCKERMIMA }}
        docker build . --file Dockerfile --tag blessingskin:test3
        docker image
        docker push devintom/blessing_skin_docker
        
