name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    #with:
       # user: ${{secrets.DOCKERUSER}
       # mima: ${{secrets.DOCKERMIMA}
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKERUSER}}/blessingskin:test3
        docker images
        docker login --username ${{secrets.DOCKERUSER}} --password-stdin ${{secrets.DOCKERMIMA}}
        docker push ${{secrets.DOCKERUSER}}/blessing_skin_docker:test3
      
